### ISSUE TITLE
Overlay opens even when the mic is muted

### ISSUE THREAD

**Issue by mjabdulm** [dwarvesf/micro-sniff#3]
Hi,

I'm using this app in Mojave 10.14.6. The overlay always pops up even if the mic is muted. I've checked the mic settings in sound preferences and Audio Midi setup. They are in mute state.

I was expecting it to popup when there is a activity on the microphone.

Thanks,
Abdul

**Comment by phucledien** [comment]
Hi @mjabdulm 😄, firstly thank you for raising the issue. We're really appreciated this 👍 

About your issue, just to clarify how the app works, the Micro Sniff app will listen to a signal in OS to show that a mic is being used or not. And the fact is, even you did mute your mic in setting, the OS can still see that it's being used and therefore send us a signal about that.

I agree with you that it's causing the wrong behavior. We will try to solve this asap.

btw, If anyone is interested in this issue, and want to contribute to this project, PRs are welcome 👍

**Comment by mjabdulm** [comment]
Hi Le Dien Phuc,

Thanks a lot for you prompt reply. Looking forward to fix.

**Comment by mjabdulm** [comment]
Hi Le Dien Phuc,

Any progress on this?

**Comment by viettrungphan** [comment]
Can't fix it since we don't listen to data from Mic to know the volume level.
